#!/bin/bash

jq -r '
  .name,
  .height,
  .weight,
  .types[0].type.name
' data.json | awk '
  NR==1 { name = toupper(substr($0,1,1)) substr($0,2) }
  NR==2 { height = $0 / 10 }  # Convert decimetres to metres
  NR==3 { weight = $0 / 10 }  # Convert hectograms to kg
  NR==4 { type = toupper(substr($0,1,1)) substr($0,2) }
  END {
    printf "%s is of type %s, weighs %.0fkg, and is %.1fm tall.\n", name, type, weight, height
  }
'
